USE cargocache;
INSERT INTO Attributes(Name,Description) VALUES ('Horror|Thriller|Western','Hx-lymphatic malign NEC');
INSERT INTO Attributes(Name,Description) VALUES ('Drama|Crime','Otalgia NOS');
INSERT INTO Attributes(Name,Description) VALUES ('Comedy|Crime|Mystery','Multiple contusion leg');
INSERT INTO Attributes(Name,Description) VALUES ('Drama|Romance|War','Sec DM hprosmlr uncntrld');
INSERT INTO Attributes(Name,Description) VALUES ('Adventure|Drama|Sci-Fi','Trans arthropathy-unspec');
INSERT INTO Attributes(Name,Description) VALUES ('Documentary|Sci-Fi','Slowing urinary stream');
INSERT INTO Attributes(Name,Description) VALUES ('Action','FU exam treatd healed fx');
INSERT INTO Attributes(Name,Description) VALUES ('Comedy|Horror','Blepharochalasis');
INSERT INTO Attributes(Name,Description) VALUES ('Comedy|Thriller','Cardiac dysrhythmia NOS');
INSERT INTO Attributes(Name,Description) VALUES ('Drama','Lacrimal fistula');
INSERT INTO Attributes(Name,Description) VALUES ('Documentary|Action','Derang lat meniscus NOS');
INSERT INTO Attributes(Name,Description) VALUES ('Comedy','Breast infect NEC-deliv');
INSERT INTO Attributes(Name,Description) VALUES ('Adventure|Drama|Romance','Bilat clft palat/lip-com');
INSERT INTO Attributes(Name,Description) VALUES ('Drama|Romance|Horror','Reiter''s disease');
INSERT INTO Attributes(Name,Description) VALUES ('Romance','Cryptogenic organiz pneu');
INSERT INTO Attributes(Name,Description) VALUES ('Action|Adventure|Sci-Fi|IMAX','Venereal disease NOS');
INSERT INTO Attributes(Name,Description) VALUES ('Comedy|Musical','Intravag tors sperm cord');
INSERT INTO Attributes(Name,Description) VALUES ('Horror','Late eff cns abscess');
INSERT INTO Attributes(Name,Description) VALUES ('Documentary','DMI o cm nt st uncntrld');
INSERT INTO Attributes(Name,Description) VALUES ('Documentary|Drama','Light-for-dates wtNOS');
INSERT INTO Attributes(Name,Description) VALUES ('Drama|Romance','TB epididymis-micro dx');
INSERT INTO Attributes(Name,Description) VALUES ('Children|Fantasy','Acquired absence kidney');
INSERT INTO Attributes(Name,Description) VALUES ('Comedy|Romance','Malign neo pineal gland');
INSERT INTO Attributes(Name,Description) VALUES ('Documentary|Comedy','Cl skul w oth fx-concuss');
INSERT INTO Attributes(Name,Description) VALUES ('Comedy|Crime|Drama|Mystery|Thriller','Polyarthritis NOS-shlder');
